package pantheonorbitalworks;

public enum RefitableFrigade {
    brawler,
    // normal_torgue_basic_brawler,
    // superb_torgue_basic_brawler,
    // legendary_torgue_basic_brawler,
    // masterwork_torgue_basic_brawler,
    // normal_torgue_advanced_brawler,
    // superb_torgue_advanced_brawler,
    // legendary_torgue_advanced_brawler,
    // masterwork_torgue_advanced_brawler,
    lasher,
    // normal_torgue_basic_lasher,
    // superb_torgue_basic_lasher,
    // legendary_torgue_basic_lasher,
    // masterwork_torgue_basic_lasher,
    // normal_torgue_advanced_lasher,
    // superb_torgue_advanced_lasher,
    // legendary_torgue_advanced_lasher,
    // masterwork_torgue_advanced_lasher,
    scarab,
    // normal_torgue_basic_scarab,
    // superb_torgue_basic_scarab,
    // legendary_torgue_basic_scarab,
    // masterwork_torgue_basic_scarab,
    // normal_torgue_advanced_scarab,
    // superb_torgue_advanced_scarab,
    // legendary_torgue_advanced_scarab,
    // masterwork_torgue_advanced_scarab,
}
